modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "btsengineconcurrent"
version = "${version}"
displayName = "BtsEngineConcurrent"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.btsengineconcurrent]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.btsengineconcurrent]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config = "btsengineconcurrent.mixins.json"

[[mixins]]
config = "btsengineconcurrent.neoforge.mixins.json"
